name: 'turtle-action'
author: 'nzws <i+action@nzws.me>'
description: 'Turtle CLI with GitHub Actions for building expo-project'
inputs:
  build-os:
    description: 'android or ios'
    required: true
  expo-sdk-version:
    description: 'version of expo sdk (ex: 36.0.0)'
    required: true
  turtle-cli-version:
    description: 'version of turtle cli'
    required: false
  working-dir:
    description: 'working directory (for example, specify a directory for monorepo)'
    required: false
outputs:
  asset-path:
    description: 'Path of the built asset'
runs:
  using: 'node12'
  main: 'build/index.js'
